imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: migrations.yml }
    - { resource: @SyliusCoreBundle/Resources/config/app/main.yml }
    - { resource: @SyliusAdminBundle/Resources/config/app/main.yml }
    - { resource: resources.yml }
    - { resource: permissions.yml }
    - { resource: grids/grids.yml }
    - { resource: services/grid.yml }

framework:
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~

twig:
    form:
        resources:
            - SyliusWebBundle:Common:forms.html.twig
            - SyliusResourceBundle::forms.html.twig
            - CmfMediaBundle:Form:fields.html.twig
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    paths:
        %kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Resources/views: PayumCore
        %kernel.root_dir%/../vendor/payum/payum/src/Payum/Stripe/Resources/views: PayumStripe

assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['SyliusWebBundle', 'CmfCreateBundle', 'SyliusResourceBundle']
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false
                dql:
                    string_functions:
                        MATCH: Sylius\Bundle\SearchBundle\Extension\Doctrine\MatchAgainstFunction

doctrine_phpcr:
    session:
        backend: %phpcr_backend%
        workspace: %phpcr_workspace%
        username: %phpcr_user%
        password: %phpcr_password%
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%

swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

payum:
    gateways:
        paypal_express_checkout:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox:   %paypal.express_checkout.sandbox%

sylius_payment:
    gateways:
        paypal_express_checkout: Paypal Express Checkout
    resources:
        payment_method:
            classes:
                model: AppBundle\Entity\PaymentMethod
                repository: AppBundle\Repository\PaymentMethodRepository
                form:
                    default: AppBundle\Form\Type\PaymentMethodType
                    choice: AppBundle\Form\Type\PaymentMethodChoiceType

sylius_product:
    resources:
        product:
            classes:
                repository: AppBundle\Repository\ProductRepository

sylius_core:
    routing:
        %sylius.model.product.class%:
            defaults:
                sylius:
                    method: findWithTaxons
                    arguments: [$id]

sylius_grid:
    templates:
        filter:
            taxon: :Grid/Filter:taxon.html.twig

sylius_user:
    resources:
        customer:
            classes:
                model: AppBundle\Entity\Customer
                form:
                    profile: AppBundle\Form\Type\CustomerProfileType
                    registration: AppBundle\Form\Type\CustomerRegistrationType
            validation_groups:
                profile: ['sylius']
                registration: ['sylius', 'app_user_registration']
        user:
            validation_groups:
                registration: ['sylius', 'app_user_registration']

sylius_cart:
    resources:
        cart_item:
            classes:
                form:
                    default: AppBundle\Form\Type\CartItemType

sylius_sequence:
    generators:
        %sylius.model.order.class%: app.generator.order_number

sylius_addressing:
    resources:
        address:
            classes:
                form:
                    default: AppBundle\Form\Type\AddressType
