imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusWebBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusAdminBundle/Resources/config/app/config.yml" }

    - { resource: "parameters.yml" }
    - { resource: "security.yml" }
    - { resource: "resources.yml" }
    - { resource: "permissions.yml" }
    - { resource: "grids/grids.yml" }
    - { resource: "services/grid.yml" }

framework:
    translator: { fallback: "%locale%" }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: true
    csrf_protection: true
    validation: { enable_annotations: true }
    templating: { engines: ["twig"] }
    default_locale: "%locale%"
    trusted_proxies: ~
    session:
        handler_id: ~

doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: UTF8

swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"

twig:
    form_themes:
        - "SyliusWebBundle:Common:forms.html.twig"
        - "SyliusResourceBundle::forms.html.twig"

fos_rest:
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }

doctrine_migrations:
    dir_name: "%kernel.root_dir%/migrations"
    namespace: App\Migrations
    table_name: app_migrations
    name: App Migrations

liip_imagine:
    filter_sets:
        category_banner:
            filters:
                thumbnail: { size: [800, 200], mode: inset }

payum:
    gateways:
        paypal_express_checkout:
            paypal_express_checkout_nvp:
                username:  %paypal.express_checkout.username%
                password:  %paypal.express_checkout.password%
                signature: %paypal.express_checkout.signature%
                sandbox:   %paypal.express_checkout.sandbox%

sylius_payment:
    gateways:
        paypal_express_checkout: Paypal Express Checkout
    resources:
        payment_method:
            classes:
                model: AppBundle\Entity\PaymentMethod
                repository: AppBundle\Repository\PaymentMethodRepository
                form:
                    default: AppBundle\Form\Type\PaymentMethodType
                    choice: AppBundle\Form\Type\PaymentMethodChoiceType

sylius_product:
    resources:
        product:
            classes:
                repository: AppBundle\Repository\ProductRepository

sylius_core:
    routing:
        %sylius.model.product.class%:
            defaults:
                sylius:
                    method: findWithTaxons
                    arguments: [$id]

sylius_grid:
    templates:
        filter:
            taxon: :Grid/Filter:taxon.html.twig

sylius_user:
    resources:
        customer:
            classes:
                model: AppBundle\Entity\Customer
                form:
                    profile: AppBundle\Form\Type\CustomerProfileType
                    registration: AppBundle\Form\Type\CustomerRegistrationType
            validation_groups:
                profile: ['sylius']
                registration: ['sylius', 'app_user_registration']
        user:
            classes:
                form:
                    registration: AppBundle\Form\Type\UserRegistrationType
            validation_groups:
                registration: ['sylius', 'app_user_registration']

sylius_cart:
    resources:
        cart_item:
            classes:
                form:
                    default: AppBundle\Form\Type\CartItemType

sylius_sequence:
    generators:
        %sylius.model.order.class%: app.generator.order_number

sylius_addressing:
    resources:
        address:
            classes:
                form:
                    default: AppBundle\Form\Type\AddressType

sylius_mailer:
    sender:
        name: BoardGameMonster
        address: bob@caponica.com
    templates:
        app.email.newsletter_subscription: :Email:newsletterSubscription.html.twig
        app.email.contact: :Email:contact.html.twig
    emails:
        app_newsletter_subscription:
            subject: app.email.newsletter_subscription.subject
            template: :Email:newsletterSubscription.html.twig
        app_contact:
            subject: app.email.contact.subject
            template: :Email:contact.html.twig
