sylius_resource:
    resources:
        app.carousel_item:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\CarouselItem
                form:
                    default: AppBundle\Form\Type\CarouselItemType
