sylius_resource:
    resources:
        app.carousel_item:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\CarouselItem
                form:
                    default: AppBundle\Form\Type\CarouselItemType
        app.category_banner:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\CategoryBanner
                form:
                    default: AppBundle\Form\Type\CategoryBannerType
        app.category_grid_item:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\CategoryGridItem
                form:
                    default: AppBundle\Form\Type\CategoryGridItemType
        app.product_grid_item:
            driver: doctrine/orm
            classes:
                model: AppBundle\Entity\ProductGridItem
                form:
                    default: AppBundle\Form\Type\ProductGridItemType
