sylius_web:
    resource: "@SyliusWebBundle/Resources/config/routing/main.yml"

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

create_image:
    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

sylius_account_profile_show:
    path: /account/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sylius_account_profile_update
        permanent: true

sylius_contact:
    path: /contact/
    methods: ['GET', 'POST']
    defaults:
        _controller: AppBundle:Contact:sendMail

app_admin:
    resource: 'routing/admin.yml'
    prefix: /admin

app_product_similar:
    path: /products/{productId}/similar/
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            paginate: false
            repository:
                method: findSimilar
                arguments: [$productId, $parameters, $limit]
            template: $template
            permission: false

app_shop_product_index:
    path: /products/
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            permission: false
            grid: sylius_shop_product
            template: SyliusWebBundle:Frontend/Product:index.html.twig

app_taxon_product_index:
    path: /t/{taxon}
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /products
        permanent: true

app_taxon_product_show:
    path: /t/{taxon}/{value}
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /products
        permanent: true
