sylius_web:
    resource: "@SyliusWebBundle/Resources/config/routing/main.yml"

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

app_admin:
    resource: 'routing/admin/admin.yml'
    prefix: /admin

app_shop:
    resource: 'routing/shop/shop.yml'
