parameters:
    sylius.controller.frontend.homepage.class: AppBundle\Controller\Frontend\HomepageController

services:
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@sylius.repository.taxon"]

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", createMainMenu]
        tags:
        - { name: knp_menu.menu, alias: menu.main}

    app.categories_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", createCategoriesMenu]
        tags:
        - { name: knp_menu.menu, alias: menu.categories}

    app.listener.image_upload:
        class: AppBundle\EventListener\ImageUploadListener
        arguments: ['@sylius.image_uploader']
        tags:
          - { name: kernel.event_listener, event: app.carousel_item.pre_create, method: uploadImage }
          - { name: kernel.event_listener, event: app.carousel_item.pre_update, method: uploadImage }
          - { name: kernel.event_listener, event: app.product_grid_item.pre_create, method: uploadImage }
          - { name: kernel.event_listener, event: app.product_grid_item.pre_update, method: uploadImage }
