parameters:
    sylius.controller.frontend.homepage.class: AppBundle\Controller\Frontend\HomepageController

services:
    app.menu.builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@sylius.repository.taxon"]

    app.menu.full_categories:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.builder", createFullCategoriesMenu]
        tags:
        - { name: knp_menu.menu, alias: menu.full_categories }

    app.menu.partial_categories:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.builder", createPartialCategoriesMenu]
        arguments:
            categories: ['Publisher', 'Game System']
        tags:
        - { name: knp_menu.menu, alias: menu.partial_categories }

    app.listener.image_upload:
        class: AppBundle\EventListener\ImageUploadListener
        arguments: ['@sylius.image_uploader']
        tags:
          - { name: kernel.event_listener, event: app.carousel_item.pre_create, method: uploadImage }
          - { name: kernel.event_listener, event: app.carousel_item.pre_update, method: uploadImage }
          - { name: kernel.event_listener, event: app.product_grid_item.pre_create, method: uploadImage }
          - { name: kernel.event_listener, event: app.product_grid_item.pre_update, method: uploadImage }

    app.admin.menu_builder_listener:
        class: AppBundle\EventListener\MenuBuilderListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addBackendMenuItems }
