parameters:
    sylius.controller.frontend.homepage.class: AppBundle\Controller\Frontend\HomepageController
    app.controller.category_banner.class: AppBundle\Controller\CategoryBannerController
    app.repository.category_banner.class: AppBundle\Repository\CategoryBannerRepository
    app.generator.order_number.class: AppBundle\Generator\OrderNumberGenerator
    sylius.checkout_form.payment.class: AppBundle\Form\Type\PaymentStepType
    sylius.form.type.user_reset_password.class: AppBundle\Form\type\UserResetPasswordType
    sylius.controller.frontend.account.order.class: AppBundle\Controller\Frontend\OrderController

services:
    app.menu.main_builder:
        class: AppBundle\Menu\MainMenuBuilder
        arguments: ["@knp_menu.factory", "@sylius.repository.taxon"]

    app.menu.dropdown_builder:
        class: AppBundle\Menu\DropdownMenuBuilder
        arguments: ["@knp_menu.factory", "@sylius.repository.taxon", "@security.authorization_checker"]

    app.menu.full_categories:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.main_builder", createFullCategoriesMenu]
        tags:
        - { name: knp_menu.menu, alias: menu.full_categories }

    app.menu.dropdown:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.dropdown_builder", createDropdownMenu]
        tags:
        - { name: knp_menu.menu, alias: menu.dropdown }

    app.menu.partial_categories:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.main_builder", createPartialCategoriesMenu]
        arguments:
            categories: ['publisher', 'game_system']
        tags:
        - { name: knp_menu.menu, alias: menu.partial_categories }

    app.listener.image_upload:
        class: AppBundle\EventListener\ImageUploadListener
        arguments: ['@sylius.image_uploader']
        tags:
          - { name: kernel.event_listener, event: app.carousel_item.pre_create, method: uploadImage }
          - { name: kernel.event_listener, event: app.carousel_item.pre_update, method: uploadImage }
          - { name: kernel.event_listener, event: app.product_grid_item.pre_create, method: uploadImage }
          - { name: kernel.event_listener, event: app.product_grid_item.pre_update, method: uploadImage }
          - { name: kernel.event_listener, event: app.category_banner.pre_create, method: uploadImage }
          - { name: kernel.event_listener, event: app.category_banner.pre_update, method: uploadImage }
          - { name: kernel.event_listener, event: app.category_grid_item.pre_create, method: uploadImage }
          - { name: kernel.event_listener, event: app.category_grid_item.pre_update, method: uploadImage }

    app.admin.menu_builder_listener:
        class: AppBundle\EventListener\MenuBuilderListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addBackendMenuItems }

    app.twig.extension.product_taxons:
        class: AppBundle\Twig\ProductTaxonsExtension
        tags:
            - { name: 'twig.extension'}

    app.generator.order_number:
        class: %app.generator.order_number.class%
        arguments: ['BGM', 1]

    app.form.type.user_change_password:
        class: AppBundle\Form\Type\UserChangePasswordType
        tags:
            - { name: form.type, alias: app_user_change_password }

    app.form.type.user_reset_password:
        class: AppBundle\Form\Type\UserResetPasswordType
        tags:
            - { name: form.type, alias: app_user_reset_password }

    sylius.form.type.customer_profile:
        class: AppBundle\Form\Type\CustomerProfileType
        arguments: [%sylius.model.customer.class%, %sylius.validation_groups.customer%, '@sylius.user.token_generator']
        tags:
            - { name: form.type, alias: sylius_customer_profile }

    sylius.form.type.customer_registration:
        class: AppBundle\Form\Type\CustomerRegistrationType
        arguments: [%sylius.model.customer.class%, %sylius.validation_groups.customer%, '@sylius.repository.customer', '@sylius.user.token_generator']
        tags:
            - { name: form.type, alias: sylius_customer_registration }

    sylius.payum.offline.action.convert_payment:
        class: AppBundle\Action\ConvertPaymentToOfflineAction
        tags:
            - { name: payum.action, factory: offline, alias: sylius.convert_payment }
