AppBundle\Entity\ProductGridItem:
    properties:
        position:
            -  NotBlank: ~
        product:
            -  NotBlank: ~
AppBundle\Entity\CarouselItem:
    properties:
        file:
            - NotBlank: ~
            - Image: ~
