AppBundle\Entity\ProductGridItem:
    properties:
        position:
            -  NotBlank: ~
        product:
            -  NotBlank: ~

AppBundle\Entity\CarouselItem:
    properties:
        file:
            - NotBlank: { groups: ['carousel_item_create'] }
            - Image: { groups: ['carousel_item_create'] }

AppBundle\Entity\Customer:
    properties:
        birthday:
            - Date: { message: 'app.customer.birthday.date' }
