AppBundle\Entity\Customer:
    type: entity
    table: sylius_customer
    fields:
        secondPhoneNumber:
            type: string
            nullable: true
        receiveNewsletter:
            type: boolean
        nickname:
            type: string
            nullable: true
        favouriteGames:
            type: text
            nullable: true
        futurePurchases:
            type: text
            nullable: true
