AppBundle\Entity\ProductGridItem:
    type: entity
    table: product_grid_item
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        position:
            type: integer
        enabled:
            type: boolean
        path:
            type: string
            nullable: true
        showRibbonHot:
            type: boolean
        showRibbonNew:
            type: boolean
        showRibbonSale:
            type: boolean
    manyToOne:
        product:
            targetEntity: Sylius\Component\Core\Model\Product
