sylius_account_profile_show:
    path: /account/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sylius_account_profile_update
        permanent: true

sylius_user_registration:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            form: sylius_customer_registration
            event: register
            template: SyliusWebBundle:Frontend/User:register.html.twig
            permission: false
            redirect:
                route: sylius_account_profile_update

sylius_user_security_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: sylius.controller.user_security:loginAction
        _sylius:
            template: SyliusWebBundle:Frontend/User:login.html.twig
            redirect:
                route: sylius_account_profile_update

sylius_account_change_password:
    path: /account/change-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.user:changePasswordAction
        _sylius:
            form: app_user_change_password

sylius_contact:
    path: /contact/
    methods: [GET, POST]
    defaults:
        _controller: AppBundle:Contact:sendMail

app_shop_product_similar:
    path: /products/{productId}/similar/
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            paginate: false
            repository:
                method: findSimilar
                arguments: [$productId, $parameters, $limit]
            template: $template
            permission: false

app_shop_product_index:
    path: /products/
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            permission: false
            grid: app_shop_product
            template: SyliusWebBundle:Frontend/Product:index.html.twig

app_shop_category_banner:
    path: /banner/
    defaults:
        _controller: app.controller.category_banner:getCategoryBannerAction
        _sylius:
            template: AppBundle:CategoryBanner:banner.html.twig

# Override default Sylius product index pages and redirect to our path
sylius_shop_by_root_taxon_product_index:
    path: /t/{rootTaxon}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: app_shop_product_index
        permanent: true

sylius_shop_by_taxon_product_index:
    path: /t/{rootTaxon}/{taxon}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: app_shop_product_index
        permanent: true

app_customer_newsletter_subscribe_guest:
    path: /subscribe/
    methods: [POST]
    defaults:
        _controller: AppBundle:Frontend/Subscription:subscribeGuest

app_customer_newsletter_subscribe_logged:
    path: /subscribe/me
    methods: [POST]
    defaults:
        _controller: AppBundle:Frontend/Subscription:subscribeLogged

app_customer_newsletter_unsubscribe:
    path: /unsubscribe/{unsubscribeToken}
    methods: [GET]
    defaults:
        _controller: AppBundle:Frontend/Subscription:unsubscribe
