imports:
    - { resource: 'admin/carousel_item.yml' }
    - { resource: 'admin/category_banner.yml' }
    - { resource: 'admin/category_grid_item.yml' }
    - { resource: 'admin/product_grid_item.yml' }
    - { resource: 'shop/product.yml' }
