sylius_grid:
    grids:
        app_admin_category_grid_item:
            driver:
                name: doctrine/orm
                options:
                    class: %app.model.category_grid_item.class%
            sorting:
                position: asc
            fields:
                position:
                    type: string
                    label: app.ui.position
                category:
                    type: string
                    label: app.ui.category_name
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: SyliusAdminBundle:Grid/Field:enabled.html.twig
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
