sylius_grid:
    grids:
        app_admin_product_grid_item:
            driver:
                name: doctrine/orm
                options:
                    class: %app.model.product_grid_item.class%
            sorting:
                position: asc
            fields:
                position:
                    type: string
                    label: app.ui.position
                product:
                    type: string
                    label: app.ui.product_name
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: SyliusAdminBundle:Grid/Field:enabled.html.twig
                showRibbonHot:
                    type: twig
                    label: app.admin.show_ribbon_hot
                    options:
                        template: SyliusAdminBundle:Grid/Field:enabled.html.twig
                showRibbonNew:
                    type: twig
                    label: app.admin.show_ribbon_new
                    options:
                        template: SyliusAdminBundle:Grid/Field:enabled.html.twig
                showRibbonSale:
                    type: twig
                    label: app.admin.show_ribbon_sale
                    options:
                        template: SyliusAdminBundle:Grid/Field:enabled.html.twig
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
